version: 2

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
      - windows
    env:
      - CGO_ENABLED=1
    main: ./cmd/versitygw
    binary: netzongw
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X=main.Build=NETZON -X=main.BuildTime={{.Date}} -X=main.Version=1.0.14

archives:
  - formats: [ 'tar.gz' ]
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # Set this to true if you want all files in the archive to be in a single directory.
    # If set to true and you extract the archive 'goreleaser_Linux_arm64.tar.gz',
    # you'll get a folder 'goreleaser_Linux_arm64'.
    # If set to false, all files are extracted separately.
    # You can also set it to a custom folder name (templating is supported).
    wrap_in_directory: true

    # use zip for windows archives
    format_overrides:
    - goos: windows
      formats: [ 'zip' ]

    files:
      - README.md
      - LICENSE
      - NOTICE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'